### ISSUE TITLE
Using Generics as return value type in Service-Endpoint leads to exception 

### ISSUE THREAD

**Issue by SebastianKuehnau** [vaadin/fusion#155]
### Description of the bug 
When I use a response data type with generics I receive an exception during runtime.

```
class PageResponse<T> {
        public List<T> content;
        public long size;
    }

    public PageResponse<Person> getPage(int page, int size) {
        var dbPage = personRepository.findAll(PageRequest.of(page, size));
    
        var response = new PageResponse<Person>();
        response.content = dbPage.getContent();
        response.size = dbPage.getTotalElements();
    
        return response;
    }
```

Here is the exception from the build log:

```
java.lang.UnsupportedOperationException: Unable to get the resolved type of class ResolvedReferenceType from T
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:286) ~[javaparser-symbol-solver-core-3.23.1.jar:na]
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:315) ~[javaparser-core-3.23.1.jar:na]
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:64) ~[javaparser-core-3.23.1.jar:na]
	at com.vaadin.fusion.generator.GeneratorType.<init>(GeneratorType.java:49) ~[fusion-endpoint-9.0.1.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at com.vaadin.fusion.generator.GeneratorType.lambda$getTypeArguments$2(GeneratorType.java:210) ~[fusion-endpoint-9.0.1.jar:na]
```

The application is working correctly although the exception message appears in the log.

### Minimal reproducible example

1. clone following project

https://github.com/SebastianKuehnau/vaadin-comparison/tree/lazy-grid/vaadin-fusion-demo

2. mvn install
3. mvn spring-boot:run and check the log
4. Application is working and display the template correctly in the browser

### Expected behavior
A startup without error message, especially if the application runs error-free after startup

### Actual behavior
Exception above shows up in the log
### Versions:
    - Vaadin / Fusion version: 9.0.1
    - Node version: 16.13.0
    - Java version: 17.01
    - OS version: mac os 12.1

**Comment by haijian-vaadin** [comment]
@Lodin let's verify if this would be fixed with the new generator.
