### ISSUE TITLE
Bad iterable handling in `ExplicitNullableTypeCheckerHelper#checkIterable`

### ISSUE THREAD

**Issue by eriklumme** [vaadin/fusion#85]
### Description of the bug 

The `ExplicitNullableTypeCheckerHelper#checkIterable` method is used to check that the type returned from an endpoint is of the expected type. It has the following code:

```
Type itemType = Object.class;
String iterableDescription = "iterable";
if (expectedType instanceof ParameterizedType) {
    itemType = ((ParameterizedType) expectedType)
            .getActualTypeArguments()[0];
    iterableDescription = "collection";
} else if (expectedType instanceof Class<?>) {
    itemType = ((Class<?>) expectedType).getComponentType();
    iterableDescription = "array";
}
```

It makes two incorrect assumptions:

### 1. If the expected type is a `ParameterizedType`, then that type argument is the type of the iterable.

Consider the `AlsoBadIterable` class in the example code. The signature is `public static class AlsoBadIterable<T> implements Iterable<Bar>`, where the actual type argument is not the type of the iterable.

Calling the `alsoBadEndpoint` produces the following error, as it attempts to invoke `getFoo()` on an instance of `Bar`.

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at com.vaadin.flow.server.connect.ExplicitNullableTypeCheckerHelper.checkBeanFields(ExplicitNullableTypeCheckerHelper.java:202) ~[fusion-endpoint-7.0.6.jar:na]
```

### 2. If the expected type is not a `ParameterizedType`, it is an array.

Consider the `BadIterable` class in the example code. The signature is `public static class BadIterable implements Iterable<Bar>`. This type is not a `ParameterizedType`, yet it is not an array.

Calling the `badEndpoint` produces the following error, as it attempts to check that the values are of type `expectedType.getComponentType()`, which is `null`.

```
java.lang.NullPointerException: null
	at com.vaadin.flow.server.connect.ExplicitNullableTypeCheckerHelper.checkValueForType(ExplicitNullableTypeCheckerHelper.java:106) ~[fusion-endpoint-7.0.6.jar:na]
```

A real-world example of this is when trying to return a Jackson `ObjectNode`, which transitively implements `Iterable<JsonNode>`, although `ObjectNode` is not parameterized.

### Minimal reproducible example

Calling the `badEndpoint` or `alsoBadEndpoint` from TypeScript results in errors.

```
import java.util.Iterator;

import com.vaadin.flow.server.auth.AnonymousAllowed;
import com.vaadin.flow.server.connect.Endpoint;

@Endpoint
@AnonymousAllowed
public class EndpointTest {

    public GoodIterable<String> goodEndpoint() {
        return new GoodIterable<>();
    }

    public BadIterable badEndpoint() {
        return new BadIterable();
    }

    public AlsoBadIterable<Foo> alsoBadEndpoint() {
        return new AlsoBadIterable<>(new Foo());
    }

    public static class GoodIterable<T> implements Iterable<T> {
        @Override
        public Iterator<T> iterator() {
            return (Iterator<T>) new BarIterator();
        }
    }

    public static class BadIterable implements Iterable<Bar> {
        @Override
        public Iterator<Bar> iterator() {
            return new BarIterator();
        }
    }

    public static class AlsoBadIterable<T> implements Iterable<Bar> {
        private final T thing;

        public AlsoBadIterable(T thing) {
            this.thing = thing;
        }

        @Override
        public Iterator<Bar> iterator() {
            return new BarIterator();
        }
    }

    public static class BarIterator implements Iterator<Bar> {
        private int i = 0;
        private final Bar[] items = new Bar[]{new Bar()};

        @Override
        public boolean hasNext() {
            return i < items.length;
        }
        @Override
        public Bar next() {
            return items[i++];
        }
    }

    public static class Foo {
        private String foo = "foo";

        public String getFoo() {
            return foo;
        }
        public void setFoo(String foo) {
            this.foo = foo;
        }
    }

    public static class Bar {
        private String bar = "bar";

        public String getBar() {
            return bar;
        }
        public void setBar(String bar) {
            this.bar = bar;
        }
    }
}
```

### Versions:
    - Vaadin / Fusion version: Vaadin 20.0.6
    - Node version: v16.7.0
    - Java version: 11

**Comment by haijian-vaadin** [comment]
Nullable change in V21 would affect this.
